local strings = {
	SI_BINDING_NAME_TB_TOGGLE_GUI	= "Вкл/Откл TraitBuddy",
	TB_KNOWN 						= "Знают",
	TB_BEING_RESEARCHED 			= "Исследуют",
	TB_COULD_RESEARCH				= "Могут изучить",
	TB_YOU_KNOW						= "Вы знаете эту особенность",
	TB_YOU_ARE_RESEARCHING			= "Вы исследуете эту способность",
	TB_YOU_COULD_RESEARCH			= "Вы можете изучить эту особенность",
	TB_ESOPLUS_CHAT					= "Статус подписки ESO Plus изменился. Войдите другими персонажми, чтобы обновить их таймеры исследования",
	TB_LINK_ACHIEVEMENT				= "Отправить достижение в чат",
	TB_MAIL_KNOWN					= "Известные особенности для %s",
	TB_MAIL_UNKNOWN					= "Неизвестные особенности для %s",
	TB_MOTIF_ALMOST					= "Почти полностью изученные",
	TB_SETS							= "Создаваемые наборы",

	-- NEW: search box placeholder
	TB_MOTIF_SEARCH_HINT				= "Введите поисковый запрос",
	
	--Options
	TB_OP_RELOAD					= "Требуется перезагрузка интерфейса /reloadui",
	TB_OP_HEADING1 					= "Выбор подсказок",
	TB_OP_HEADING2 					= "Внешний вид подсказки",
	TB_OP_HEADING4					= "Управление персонажами",
	TB_OP_HEADING6					= "Иконка в инвентаре",
	TB_OP_KNOWN						= "Раздел 'Знают'",
	TB_OP_KNOWN_TT					= "Включить раздел 'Знают'",
	TB_OP_KNOWN_COLOUR				= "Цвет раздела 'Знают'",
	TB_OP_KNOWN_COLOUR_TT			= "Выбор цвета раздела 'Знают'",
	TB_OP_RESEARCHING				= "Раздел 'Исследуют'",
	TB_OP_RESEARCHING_TT			= "Включить раздел 'Исследуют'",
	TB_OP_RESEARCHING_COLOUR		= "Цвет раздела 'Исследуют'",
	TB_OP_RESEARCHING_COLOUR_TT		= "Выбор цвета раздела 'Исследуют'",
	TB_OP_CANRESEARCH				= "Раздел 'Могут изучить'",
	TB_OP_CANRESEARCH_TT			= "Включить раздел 'Могут изучить'",
	TB_OP_CANRESEARCH_COLOUR		= "Цвет раздела 'Могут изучить'",
	TB_OP_CANRESEARCH_COLOUR_TT		= "Выбор цвета раздела 'Могут изучить'",
	TB_OP_YOUKNOW					= "Раздел 'Резюме'",
	TB_OP_YOUKNOW_TT				= "Включить раздел 'Резюме' снизу описания",
	TB_OP_BAG						= "Сумка",
	TB_OP_BAG_TT					= "Расширять описание предметов в сумке. Используется во многих местах, в том числе в инвентаре и банке",
	TB_OP_LOOT						= "Подбор",
	TB_OP_LOOT_TT					= "Расширять описание подбираемых предметов",
	TB_OP_MAIL						= "Почта",
	TB_OP_MAIL_TT					= "Расширять описание предметов в почте",
	TB_OP_BUYBACK_TT				= "Расширять описание предметов в меню 'Возврат' у торговцев",
	TB_OP_TRADE						= "Торговля",
	TB_OP_TRADE_TT					= "Расширять описание подкупаемых предметов",
	TB_OP_TRADINGHOUSE				= "Гильдейские торговцы",
	TB_OP_TRADINGHOUSE_TT			= "Расширять описание предметов в магазине гильдии",
	TB_OP_CHAT						= "Чат",
	TB_OP_CHAT_TT					= "Расширять описание предметов, отправляемых в чат",
	TB_OP_SELECTION					= "Альтернативный выбор персонажа",
	TB_OP_SELECTION_TT				= "Переключать персонажей с помощью выпадающего меню или иконок",
	TB_OP_QUEST						= "Квестовая награда",
	TB_OP_QUEST_TT					= "Расширять описание квестовых наград",
	TB_OP_CRAFTING_TT				= "Расширять описание создоваемых предметов",
	TB_OP_INCLUSION					= "Показывать следующих персонажей в TraitBuddy",
	TB_OP_WORN_TT					= "Расширять описание экипирированных предметов",
	TB_OP_UI_KNOW_COLOUR			= "Цвет инонки 'Известно'",
	TB_OP_UI_KNOW_COLOUR_TT			= "Выбор цвета галки 'Известно'",
	TB_OP_UI_RESEARCHING_COLOUR		= "Цвет иконки 'Исследуется'",
	TB_OP_UI_RESEARCHING_COLOUR_TT	= "Выбор цвета иконки часов 'Исследуется'",
	TB_OP_UI_OTHERS_KNOW_COLOUR		= "Цвет инонки 'Известно для других персонажей'",
	TB_OP_UI_OTHERS_KNOW_COLOUR_TT	= "Выбор цвета галки 'Известно для других персонажей'",
	TB_OP_UI_OTHERS_RES_COLOUR		= "Цвет инонки 'Исследуется другими персонажами'",
	TB_OP_UI_OTHERS_RES_COLOUR_TT	= "Выбор цвета иконки часов 'Исследуется другими персонажами'",
	TB_OP_UI_NOTKNOWN_COLOUR		= "Цвет инонки 'Не известно'",
	TB_OP_UI_NOTKNOWN_COLOUR_TT		= "Выбор цвета креста 'Не известно'",
	TB_OP_DELETE_TT					= "Удалить %s для %s",
	TB_OP_ESOPLUS					= "Напоминание при изменении статуса ESO Plus",
	TB_OP_ESOPLUS_TT				= "Подписка ESO Plus влияет на скорость исследования",
	TB_OP_TITLE						= "Показать заголовок",
	TB_OP_TITLE_TT					= "Показывать тип предмета и особенность в подсказке",
	TB_OP_LAUNCH1					= "Добавить кнопку на ремесленные станции",
	TB_OP_LAUNCH2					= "Добавить кнопку на экран навыков",
	TB_OP_LAUNCH3					= "Добавить кнопку в магазин гильдии",
	TB_OP_TIDY						= "Автоудаление данных о старых персонажах",
	TB_OP_TIDY_TT					= "Автоматически удалять данные TraitBuddy для персонажей, которых больше не существует",
	TB_OP_ADDON1					= "Использовать Inventory Insight",
	TB_OP_ADDON1_TT					= "Использовать дополнение Inventory Insight для отображения резюме на подсказках, если установлено. Может работать медленно",
	TB_OP_INV_BAG_TT				= "Показывать иконки в инвентаре",
	TB_OP_INV_BANK_TT				= "Показывать иконки в банке",
	TB_OP_INV_OTHER					= "Другой персонаж может изучить",
	TB_OP_INV_OTHER_TT				= "Цвет иконки, используемый, когда другой персонаж может изучить особенность или мотив",
	TB_OP_COMPLETE					= "Уведомление при завершении исследования",
	TB_OP_COMPLETE_TT				= "Отображать специальное сообщение TraidBuddy, когда исследование особенности на текущем персонаже завершено",
	TB_OP_IGV_ONTOP					= "Иконка поверх Inventory Grid View",
	TB_OP_IGV_ONTOP_TT				= "Отрисовывать иконку поверх предмета при использовании дополнения Inventory Grid View",
	TB_OP_MOTIFLOC					= "Показать расположение мотива",
	TB_OP_MOTIFLOC_TT				= "Добавлять во всплывающую подсказку мотива информацию о том, где его можно найти",
	TB_OP_GAME_ICON					= "Использовать стандартный значок",
	TB_OP_GAME_ICON_TT				= "Использовать стандартный значок исследования TESO, добавленный в дополнении Clockwork City",
	TB_OP_UI_MARK_COLOUR			= "Цвет отмеченной особенности",
	TB_OP_UI_MARK_COLOUR_TT			= "Выбор цвета отмеченной особенности",
	TB_MARK_TRAIT					= "Отметить особенность",
	TB_UNMARK_TRAIT					= "Снять отметку",
}

if GetString(SI_BINDING_NAME_TB_TOGGLE_GUI):len() == 0 then
	for key,value in pairs(strings) do
		SafeAddVersion(key, 1)
		ZO_CreateStringId(key, value)
	end
end